-- Schema da API de Tabela Tarifaria de Agua (gerenciado pelo Flyway).

CREATE TABLE tabela_tarifaria (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    data_vigencia DATE         NOT NULL,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE faixa_consumo (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_id      BIGINT        NOT NULL REFERENCES tabela_tarifaria (id) ON DELETE CASCADE,
    categoria      VARCHAR(20)   NOT NULL,
    inicio         INTEGER       NOT NULL,
    fim            INTEGER       NOT NULL,
    valor_unitario NUMERIC(12,2) NOT NULL,
    CONSTRAINT chk_faixa_ordem  CHECK (inicio < fim),
    CONSTRAINT chk_faixa_inicio CHECK (inicio >= 0),
    CONSTRAINT chk_faixa_valor  CHECK (valor_unitario > 0),
    CONSTRAINT uq_faixa_inicio  UNIQUE (tabela_id, categoria, inicio)
);

CREATE INDEX idx_faixa_tabela_categoria ON faixa_consumo (tabela_id, categoria, inicio);
